### ISSUE TITLE
Setup project from geonode template project

### ISSUE THREAD

**Issue by jj0hns0n** [state-hiu/2C-GeoNode#1]
Setup the 2c_geonode project from the geonode-template project

* [x] Create project from the template
* [x] Verify the virtualenvironment setup works
* [x] Verify the docker setup works
* [x] Verify the ansible setup works
* [x] Verify the paver setup works (with latest geoserver)

**Comment by jj0hns0n** [comment]
Basic project added at 542e12150d102778044b1931b56887085452d54b

**Comment by kalxas** [comment]
Done.
