### ISSUE TITLE
Bulk Upload: Bounding Boxes

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#116]
Data and metadata representing the bounding boxes used to clip SRTM and WorldPop data for 10 cities are ready to be uploaded from here:

https://drive.google.com/open?id=0B2Oc3HZSI7QFeGkwNXhSSy1sUk0

**Comment by kalxas** [comment]
Data uploaded to http://2c.terranodo.io

**Comment by kalxas** [comment]
Data uploaded to http://secondarycities.geonode.state.gov
