### ISSUE TITLE
Create SLDs for new Esmeraldas and Cusco raster layers

### ISSUE THREAD

**Issue by kalxas** [state-hiu/2C-GeoNode#119]
http://2c.terranodo.io/layers/geonode:ras10
http://2c.terranodo.io/layers/geonode:ras17
http://2c.terranodo.io/layers/geonode:ras09
http://2c.terranodo.io/layers/geonode:esmeraldas_floodsusceptibility_30m
http://2c.terranodo.io/layers/geonode:esmeraldas_dsm_5m
http://2c.terranodo.io/layers/geonode:esmeraldas_massmovementssusceptibility_30m
http://2c.terranodo.io/layers/geonode:esmeraldas_dtm_5m

**Comment by schignel** [comment]
If easy, the following layers can have the "elevation" style applied to them:

http://2c.terranodo.io/layers/geonode:esmeraldas_dsm_5m
http://2c.terranodo.io/layers/geonode:esmeraldas_dtm_5m

**Comment by schignel** [comment]
Hi @kalxas, ras09, ras10, and ras17 are all satisfaction heat maps, so I've created a single style to applied to all of them (attached). This should scale to each layer's min/max values if possible.


[Satisfaction.zip](https://github.com/state-hiu/2C-GeoNode/files/1386655/Satisfaction.zip)

**Comment by schignel** [comment]
Attached are styles for the two susceptibility rasters:

http://2c.terranodo.io/layers/geonode:esmeraldas_massmovementssusceptibility_30m
http://2c.terranodo.io/layers/geonode:esmeraldas_floodsusceptibility_30m

[Susceptibility.zip](https://github.com/state-hiu/2C-GeoNode/files/1386683/Susceptibility.zip)

**Comment by kalxas** [comment]
Thanks @schignel 
I will add those layers in the raster spreadsheet, add the new templates and re-run the process.

**Comment by kalxas** [comment]
Done!

**Comment by kalxas** [comment]
Please check here:
http://2c.terranodo.io/layers/?limit=100&offset=0&type__in=raster

**Comment by kalxas** [comment]
Deployed to production too

**Comment by schignel** [comment]
Looking good, thanks @kalxas. I think we can close.
