### ISSUE TITLE
Bulk Upload: New metadata spreadsheet for HydroAnalysis and Santiago SRTM and WorldPop

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#122]
The two "old" versions of these metadata spreadsheets have been updated with the NEW metadata spreadsheet--adding missing fields and removing unnecessary fields. These are for the:

HydroAnalysis layers: https://docs.google.com/spreadsheets/d/1VxuHtfyrwuFSczoEVdhaFDBaBnukFvAdQu-7zszp538/edit#gid=1991486483

and

Santiago SRTM_WorldPop: https://docs.google.com/spreadsheets/d/1npM8VyDZ8BPgT5CxyedCv22OiWkquSluQHuK839LMwY/edit#gid=1991486483

**Comment by kalxas** [comment]
@sophialinn metadata uploaded on 2c.terranodo.io

**Comment by kalxas** [comment]
Needs review

**Comment by kalxas** [comment]
Metadata uploaded on production site
