### ISSUE TITLE
Create instructions for the Bulk Upload process

### ISSUE THREAD

**Issue by kalxas** [state-hiu/2C-GeoNode#124]

**Comment by kalxas** [comment]
We will use #120 as a use case to create the instructions

**Comment by kalxas** [comment]
File shared through Google Drive

**Comment by kalxas** [comment]
Waiting review from @d3netxer

**Comment by d3netxer** [comment]
I can try reviewing and trying bulk upload tomorrow @kalxas

**Comment by kalxas** [comment]
@d3netxer I am closing this since you managed to complete an upload successfully.
