### ISSUE TITLE
Bulk Upload: Esmeraldas metadata spreadsheet--"Categories" correction

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#125]
The metadata spreadsheet for Esmeraldas has been corrected. All erroneous Categories have been removed and proper categories have been assigned. New spreadsheet can be found here:
https://docs.google.com/spreadsheets/d/10qfuPeWlazbe8l1IF_fzQb2GBzYwdVD_VRWyq2e66SU/edit?usp=sharing

**Comment by kalxas** [comment]
Categories were corrected on the beta site based on the provided spreadsheet.
The only issue is that "Risk" category seems to still be there, perhaps from another spreadsheet?

**Comment by kalxas** [comment]
ok, Risk removed too

**Comment by kalxas** [comment]
Fixed
