### ISSUE TITLE
Bulk Upload: Santiago GHSL

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#126]
The Global Human Settlement Layer (GHSL) data and metadata for Santiago are ready to be uploaded.  Here's the link to the data and metadata: https://drive.google.com/open?id=0B2Oc3HZSI7QFazhqdEhXUkVOVFU

**Comment by sophialinn** [comment]
This issue is redundant with issue #120

**Comment by kalxas** [comment]
Closing as duplicate of #120
