### ISSUE TITLE
Bulk Upload: Douala SRTM

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#139]
Data and metadata are ready to be uploaded for the SRTM-derived layers for Douala:
https://drive.google.com/drive/folders/1qVmURr0ag0QLBD_cxcd9GEgOzIB1ahQT?usp=sharing

**Comment by kalxas** [comment]
Uploaded to beta site.
The datasets were used to compile the Bulk Upload instructions manual.

**Comment by kalxas** [comment]
@d3netxer would you like to try to use the instructions to upload the data to the production site?

**Comment by d3netxer** [comment]
I tried the bulk upload. I think it may have worked. Are the rasters supposed to have custom styles? They seem to be generic. Also the layers only show up when I log in. Is this supposed to happen? @kalxas

**Comment by kalxas** [comment]
@d3netxer did you use the update_permissions_from_list.py script to reset permissions after updating the metadata?

**Comment by kalxas** [comment]
The bulk upload worked, I can see the layers. 👍 
The permissions do not seem to have been properly set.
Please reset the permissions (with environment set properly):
```$ python update_permissions_from_list.py Douala\ SRTM\ Metadata\ Spreadsheet.csv```

**Comment by d3netxer** [comment]
ok @kalxas I ran the permissions script and it worked. Some of the rasters don't have a style. Is this expected?

**Comment by kalxas** [comment]
Yes, the raster styles are defined through another process which is not documented yet.
I will add this part on the document next week

**Comment by kalxas** [comment]
Raster styles updated

**Comment by kalxas** [comment]
Completed according to last e-mail from @faithrs
