### ISSUE TITLE
Remove "Bad" Datasets

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#140]
These datasets need to be removed from the 2C GeoNode database. (Can you see this spreadsheet?)

[REMOVE_metadata_2017-11-02_original.xlsx](https://github.com/state-hiu/2C-GeoNode/files/1455907/REMOVE_metadata_2017-11-02_original.xlsx)

**Comment by kalxas** [comment]
2 options here:
1. Create a script to remove those datasets using the list
2. Remove manually from the admin web tool (http://secondarycities.geonode.state.gov/admin/)

**Comment by sophialinn** [comment]
Doesn't matter to me! Whichever is most efficient.

**Comment by sophialinn** [comment]
Just to check to see if it were possible, I went to the 'live' 2C GeoNode, signed in as an admin, and tried to delete one of the bad layers (centro_acopio_1). It seems to be GONE now. So that will work, but will be somewhat tedious to do for 315 layers.

**Comment by melindajean** [comment]
I think we need to manually remove the layers.  Can we get started on this?

**Comment by kalxas** [comment]
@sophialinn I think it is easier if you use this admin page:
http://secondarycities.geonode.state.gov/admin/layers/layer/
and select the layers to delete like this:

![screenshot_20171130_005405](https://user-images.githubusercontent.com/383944/33403412-fdf199b8-d568-11e7-9c12-a29e99b79570.png)

**Comment by kalxas** [comment]
There is also a search tool on top of that page

**Comment by sophialinn** [comment]
Excellent! Thanks. I'll let you know if I have any questions or trouble but will try to delete all 315 layers this way.

**Comment by kalxas** [comment]
you are welcome

**Comment by kalxas** [comment]
Fixed by @sophialinn 
Thanks!

**Comment by sophialinn** [comment]
An additional 34 layers have been deleted. These were ones that ECB reviewed and determined were "old" or redundant.
