### ISSUE TITLE
testing on dev 2C GeoNode

### ISSUE THREAD

**Issue by d3netxer** [state-hiu/2C-GeoNode#174]
on June 11, 2019

Layers:

- Filters: skipped testing because they are not implemented

Kharkiv: Forest Roads
	-on dataset page, it does not appear on the preview map, and the legend does not appear
	-404 error when try to download
	
Kharkiv: "Rivers" (may be canals)
	- looks good
	
Denpasar: Roads
	- no thumbnail. I logged in a set the thumbnail, but it still doesn't show up.
	
Medellin: Green Corridors
	- looks good

-maybe it would be better if the zipfile names weren't all the same.	
test metadata

-was not able to delete Pokhara: Births 2020 (adjusted) from interface (was logged in), or from admin interface
-Indore: Hillshade, 

-Search works good

-not able to upload a shapefile, received 'unexpected error'

Documents:
- not able to download any of them

WMS service: 
- Is not working for me, but maybe I am doing it wrong. Any help here?

other:

-layers do not show when http version of the site it used. Might as well just do an auto-redirect to https version.

GeoNode front-page:

- add new cities
- search bar: add some bottom padding to magnifying glass
- fix alignment for icons
- fix alignment of the 'Explore all datasets' title

Admin interface: Can we add users to groups?

**Comment by kalxas** [comment]
Adding feedback from Amanda and Hanna:
These are the key observations:
-          One cannot download raster files (from what I observed) without a login.
-          Layers that were broken before on 2.4 are still broken.
-          I have not observed a problem with the PRJ file or any other projection issues except with workshop data for specifically Medellin. 
- The names of the zipped shapefiles are not useful

**Comment by kalxas** [comment]
Raster download issue reported in #175

**Comment by d3netxer** [comment]
adding more things we discussed at the meeting today:
- sorting button is not working
- The correct files are not showing for the 'original dataset' download option

**Comment by kalxas** [comment]
In order to be able to discuss those findings separately, I will open new issues for each one of them with the "migration" label.

**Comment by kalxas** [comment]
All reports now have a separate issue for discussion. Thanks!
