### ISSUE TITLE
Raster data download not working for anonymous user

### ISSUE THREAD

**Issue by kalxas** [state-hiu/2C-GeoNode#175]
e.g. https://2c.puerti.co/layers/col_ppp_v2b_2015_unadj

**Comment by kalxas** [comment]
actually "download original data" works fine, it is the GeoServer downloads that do not work

**Comment by ingenieroariel** [comment]
GeoServer blocks the download asking for permissions even when the layer is viewable by the public.

**Comment by ingenieroariel** [comment]
Let's leave the Download Original data links on raster + vector advertising only what works and create an issue upstream to ask for advice.

Things we tested:

 - [x] Permission for anon users to download in Django (working)
 - [x] Permission for anon users being propagated to GeoFence (working)  
 - [x] Proxy-base url setting to correct public url (working)
 - [x] oauth2 application workflow links, checked there is no trailing slash (working)

**Comment by kalxas** [comment]
This is related to the issue of not being able to log in from GeoServer with GeoNode credentials

**Comment by kalxas** [comment]
Issue fixed now, please confirm.

**Comment by d3netxer** [comment]
I tested right now not being logged in, but it prompts me with a Sign-in pop-up box.

**Comment by kalxas** [comment]
this is weird, it was working yesterday, need to check if something got reverted.

**Comment by kalxas** [comment]
This issue is not about permissions, but about download links.
The GeoTiff link points to the /gs/ endpoint, e.g. https://2c.puerti.co/gs/wcs?service=WCS&format=image%2Ftiff&request=GetCoverage&srs=EPSG%3A4326&version=2.0.1&bbox=-75.744656771200000%2C6.058262631600000%2C-75.363005371200000%2C6.505744731600000&coverageid=col_ppp_v2b_2015_unadj
This link will not work for anonymous user, while the https://2c.puerti.co/geoserver/wcs?service=WCS&format=image%2Ftiff&request=GetCoverage&srs=EPSG%3A4326&version=2.0.1&bbox=-75.744656771200000%2C6.058262631600000%2C-75.363005371200000%2C6.505744731600000&coverageid=col_ppp_v2b_2015_unadj works fine.

**Comment by kalxas** [comment]
Some interesting upstream links:
https://github.com/GeoNode/geonode/issues/4227
https://github.com/GeoNode/geonode/pull/4208
https://github.com/GeoNode/geonode/pull/4226

**Comment by kalxas** [comment]
After upgrading to latest geonode master, this issue seems to be fixed.
Can you please confirm?

**Comment by kalxas** [comment]
Fixed
