### ISSUE TITLE
Missing thumbnails in 2.10 development server

### ISSUE THREAD

**Issue by kalxas** [state-hiu/2C-GeoNode#178]
Report from @d3netxer 
Denpasar: Roads
- no thumbnail. I logged in a set the thumbnail, but it still doesn't show up.

**Comment by kalxas** [comment]
@d3netxer setting the thumbnail works for me.
Did you make sure to empty your cache before reloading the page?

**Comment by d3netxer** [comment]
ok great, I emptied my cache and it worked!
