### ISSUE TITLE
Kharkiv: Forest Roads dataset broken

### ISSUE THREAD

**Issue by kalxas** [state-hiu/2C-GeoNode#179]
It was working fine in production:
https://secondarycities.geonode.state.gov/layers/geonode:kha_forestroad_spaero#map=69.84927440351807/4039066.43/6446292.19/0

Dev:
https://2c.puerti.co/layers/kha_forestroad_spaero#/

**Comment by kalxas** [comment]
Fixed in http://2c.puerti.co/layers/kha_forestroad_spaero#/

**Comment by arshores** [comment]
This is fixed
