### ISSUE TITLE
The names of the zipped shapefiles are not useful

### ISSUE THREAD

**Issue by kalxas** [state-hiu/2C-GeoNode#180]
Reported both by @arshores and @d3netxer 

When downloading "Zipped Shapefile" in 2.10, the "ows.zip" filename is always used. In 2.6 the file name reflected the layer name.

**Comment by kalxas** [comment]
@ingenieroariel I think this one has to do with docker deployment configuration, right?

**Comment by kalxas** [comment]
This is also related to the /gs/ endpoint. If we replace gs with geoserver in the download link, the zip name is correct.

**Comment by kalxas** [comment]
This has been fixed. Please review

**Comment by d3netxer** [comment]
This is working now for me.
