### ISSUE TITLE
Sorting button is not working in 2.10

### ISSUE THREAD

**Issue by kalxas** [state-hiu/2C-GeoNode#181]
Original page:
https://secondarycities.geonode.state.gov/layers/?limit=100&offset=0&order_by=title

Dev page:
https://2c.puerti.co/layers/?limit=50&offset=0&order_by=title

**Comment by kalxas** [comment]
Working now on 2.10. Please review

**Comment by sophialinn** [comment]
none of the sorting options are working, 7/30/2019 on http://2c.puerti.com
