### ISSUE TITLE
Enable search filters on 2.10

### ISSUE THREAD

**Issue by kalxas** [state-hiu/2C-GeoNode#189]
Production site:
![image](https://user-images.githubusercontent.com/383944/59910035-b697b680-9419-11e9-8eca-4a009f19b559.png)

Dev site:
![image](https://user-images.githubusercontent.com/383944/59910086-da5afc80-9419-11e9-9637-ef4e6072de74.png)

**Comment by arshores** [comment]
Just checked on this issue and it has not yet been fixed. This would be apart of contract 1 I suppose that would need to be fixed before going live?

**Comment by kalxas** [comment]
yes, we will enable those filters, thanks for the reminder

**Comment by kalxas** [comment]
city and dataprovider type filters now added

**Comment by kalxas** [comment]
and keywords enabled now

**Comment by kalxas** [comment]
Based on discussions on e-mail, keywords filter has been disabled. Users can search for keywords using the text filter that implements a full text search in 2.10.
