### ISSUE TITLE
Layer page needs to be upgraded so the extra fields can be viewed

### ISSUE THREAD

**Issue by kalxas** [state-hiu/2C-GeoNode#192]

**Comment by kalxas** [comment]
Done, please review:
https://2c.puerti.co/layers/kha_adm_bound_poly_spaero#more

**Comment by arshores** [comment]
Do you mean that you can click on the more info button and get the rest of the metadata? I wasn't aware that was a problem but if it was, it is now fixed.

**Comment by kalxas** [comment]
Yes, this was missing from the migrated code and Ariel fixed it.
