### ISSUE TITLE
BULK UPLOAD: City Boundaries

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#193]
The data and metadata in this folder are ready for upload. These are NEW datasets from 2C-CSU:

[https://drive.google.com/open?id=1Hs_chgRra4Aq9q1iwXqAMcaF5xPRL8oW](url)

**Comment by kalxas** [comment]
Finished processing 18 layers in 949.0 seconds.

18 Created layers
0 Updated layers
0 Skipped layers
0 Failed layers
52.722222 seconds per layer

**Comment by kalxas** [comment]
metadata updated from spreadsheet, only this layer did not update:

https://2c.puerti.co/layers/geonode:ind_dviaadm2#/

**Comment by kalxas** [comment]
```
indore: diva-gis boundary : Failed to update                                                
Exception: Layer matching query does not exist.
```

**Comment by kalxas** [comment]
For the failed layer, the name of the data file does not match the name in the spreadsheet, easy to fix

**Comment by kalxas** [comment]
Issue fixed. Please review:
https://2c.puerti.co/layers/?limit=50&offset=0&order_by=-date

**Comment by sophialinn** [comment]
Ok,  let's set up a time to focus on fixing these little issues. I'm en route from southern Colorado. Hope to call in to our call if we have cell service at that time! Back in the office later today or tomorrow for sure.


Sent from my smartphone


-------- Original message --------

**Comment by arshores** [comment]
Seems good to go.
