### ISSUE TITLE
BULK UPLOAD: Douala Water Features

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#194]
This is just a single dataset (and metadata), but we can use it as a test to REPLACE an existing layer (that I had uploaded as a TEST last week).

[https://drive.google.com/open?id=1cGOIMv6kFvXRGs79mOI5P2ER2RfOx-eg](url)

**Comment by kalxas** [comment]
```
Finished processing 1 layers in 40.0 seconds.

0 Created layers
1 Updated layers
0 Skipped layers
0 Failed layers
40.000000 seconds per layer
```

**Comment by kalxas** [comment]
Metadata updated, please review:
https://2c.puerti.co/layers/geonode:dou_waterosm#/

**Comment by arshores** [comment]
I get a 403 forbidden error when I flick on the above link. I'm not sure what to do to test this. It seems as though it worked from the message above so I will close this out.

**Comment by kalxas** [comment]
Good catch @arshores we need to update the permissions on the newly uploaded data, so that they are visible to the anonymous user.

**Comment by kalxas** [comment]
Fixed

**Comment by arshores** [comment]
Will this need to be continually updated on any new data that is added? Just wondering if I should keep my eye out for this issue in the future after the bulk uploads

**Comment by kalxas** [comment]
We do have a script for resetting the permissions, exactly as we had in place for 2.6 bulk uploads.
I just forgot to run this script :)
