### ISSUE TITLE
BULK UPLOAD: Douala WorldPop (4 datasets)

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#201]
These data and metadata are ready to be uploaded:
https://drive.google.com/drive/folders/1fqqpdl6LzJAwyKwfweuXaAGh2sTxX3Qg?usp=sharing

**Comment by kalxas** [comment]
Is this a duplicate of https://github.com/state-hiu/2C-GeoNode/issues/195 ?

**Comment by kalxas** [comment]
Not a duplicate after all, the upload has already happened, please review.

https://secondarycities.geonode.state.gov/layers/?limit=50&offset=0&order_by=-date

**Comment by kalxas** [comment]
```
Finished processing 4 layers in 178.0 seconds.

4 Created layers
0 Updated layers
0 Skipped layers
0 Failed layers
44.500000 seconds per layer
```

**Comment by kalxas** [comment]
```
Douala: Population 2010 (adjusted) : Metadata updated!
Douala: Population 2015 (adjusted) : Metadata updated!
Douala: Population 2010 : Metadata updated!
Douala: Population 2015 : Metadata updated!
```

**Comment by kalxas** [comment]
This one also does not have errors reported, can we close?
