### ISSUE TITLE
Cannot connect to ANY data detail page

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#210]
From the data layers list, I click on any data layer and it just stalls/spins and never connects to the data detail page. I wanted to test out downloading some of the newly uploaded data sets, but can't get there today...

An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.
If you are the system administrator of this resource then you should check the [error log](http://nginx.org/r/error_log) for details.
Faithfully yours, OpenResty.

**Comment by kalxas** [comment]
Fixed, can you please check again?

**Comment by sophialinn** [comment]
Yes, it's working now. (Let's hope it keeps working! ;) )
