### ISSUE TITLE
Error when clicking on a layer page

### ISSUE THREAD

**Issue by arshores** [state-hiu/2C-GeoNode#224]
This error comes up when I click on a layer:
An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, OpenResty.

**Comment by kalxas** [comment]
This message is shown during a restart of the server, can you please try again now?
It works for me.

**Comment by arshores** [comment]
I'm still getting the error

**Comment by kalxas** [comment]
Please clear your browser cache and try again.

**Comment by arshores** [comment]
Cleared cache and still getting error.

**Comment by kalxas** [comment]
Can you please post the url you are getting error from?

**Comment by arshores** [comment]
https://secondarycities.geonode.state.gov/layers/tecorregion_z19

**Comment by kalxas** [comment]
![image](https://user-images.githubusercontent.com/383944/65169825-0f461200-da50-11e9-9f8e-82d5cff9c406.png)

**Comment by kalxas** [comment]
@d3netxer @sophialinn can you please confirm you can see this page correctly?

**Comment by d3netxer** [comment]
yes, I see the page correctly. @arshores can you try using a different browser or computer?

**Comment by arshores** [comment]
Got this error when I tried using firefox
503 ERROR
The request could not be satisfied.
The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions.
If you received this error while trying to use an app or access a website, please contact the provider or website owner for assistance.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by following steps in the CloudFront documentation (http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-503-service-unavailable.html).

Generated by cloudfront (CloudFront)
Request ID: CL0NS-jicIhqsi2Pk7Knu7igkCqL95nqkktbm4QRA-NS_ENIZ0Rs7Q==

**Comment by arshores** [comment]
Just to clarify, that was when trying to get to the GeoNode only, not when clicking on a layer.

**Comment by arshores** [comment]
Let me restart my computer

**Comment by arshores** [comment]
I cannot access the GeoNode from any browser now. Maybe it is a CSU network problem?

503 ERROR
The request could not be satisfied.
The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions.
If you received this error while trying to use an app or access a website, please contact the provider or website owner for assistance.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by following steps in the CloudFront documentation (http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-503-service-unavailable.html).
Generated by cloudfront (CloudFront)
Request ID: a_tNR6E77JxLkvS75PmN2Em29QuDhfAu0RPjkwDpKUja5waHb5PKuA==

**Comment by d3netxer** [comment]
That is odd, we don't have a CloudFront distribution set up for secondarycities.geonode.state.gov

**Comment by arshores** [comment]
It isn't the network on our end.

**Comment by sophialinn** [comment]
I'm at a conference in Denver and just logged on the hotel network. I can see the geonode just fine from here.

**Comment by arshores** [comment]
I had other people check and it isn't working for them. I have no idea at this point what might be the issue. I'm getting that same error when I try to get to the 2C website as well.

**Comment by d3netxer** [comment]
I have been working on re-deploying the 2C website using S3 hosting. The last thing I have been working on is adding edge lambdas to add some needed headers. I'll let you know when this is done, so you can check the 2C website. I don't think any of this should have affected the 2C GeoNode site though.

**Comment by d3netxer** [comment]
I should have the headers now where I want them. @arshores do you mind checking https://secondarycities.state.gov/ and if it gives and error, can you take a screenshot of your screen?

**Comment by arshores** [comment]
All is well now.

**Comment by arshores** [comment]
Might be good to reflect on why that happened/why there wasn't an issue for
some but for others, they couldn't access to website or GeoNode.
Kind Regards,

Amanda R. Shores, PhD
Project Manager and Post Doctoral Scholar
Secondary Cities
Colorado State University
___________________________________________

*Light the fire of imagination and seek the realization of a better
tomorrow for all.*

**Comment by ingenieroariel** [comment]
The issue was caused by AWS configuration outside of GeoNode. It is true
that it would be good to investigate how to do those changes in the future
without downtime but that is probably an issue for a different GitHub repo.
The main 2C website one perhaps?
