### ISSUE TITLE
BULK UPLOAD: Mekelle (7 datasets)

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#230]
Mekelle data are ready to be uploaded. There are seven datasets.

Data is here: https://drive.google.com/open?id=1t_Kz2gOLUO2bSE_8HdzMOzW1Uu0RBjux

Metadata is here: https://docs.google.com/spreadsheets/d/1vvIfJjYWGwOYe4GVhNt8gP9SWrC7Zd077Hko8jpH07Q/edit?usp=sharing

**Comment by kalxas** [comment]
The Data link goes to one file, not the containing folder

**Comment by kalxas** [comment]
found them

**Comment by kalxas** [comment]
```
Finished processing 7 layers in 361.0 seconds.

7 Created layers
0 Updated layers
0 Skipped layers
0 Failed layers
51.571429 seconds per layer
```

**Comment by kalxas** [comment]
```
Mekelle: City Boundary : Metadata updated!
Mekelle: Public Toilets : Metadata updated!
Mekelle: Water Supply Pipe Network : Metadata updated!
Mekelle: Water Wells : Metadata updated!
Mekelle: Taxi Route : Metadata updated!
Mekelle: Taxi Stops : Metadata updated!
Mekelle: Mekelle University Physical assets : Metadata updated!
```

**Comment by sophialinn** [comment]
Waiting to make minor edit to capitalization in metadata before closing issue.

**Comment by sophialinn** [comment]
Also, need to check Mekelle Bus Stations

**Comment by kalxas** [comment]
ah, that was not in the spreadsheet?

**Comment by sophialinn** [comment]
Hmm. The Bus Stop layer was not in the most recent collection of data sets, but since I didn't actually give you the link to the proper folder, perhaps that was a mix-up. 

Here's the link to the [Mekelle Data (Sept 2019)](https://drive.google.com/open?id=1tn6xKP2JUq1R51LEE6mR2zo59JgnuTq1) data that ought to correspond to the metadata.

Actually, I'm seeing some problems in the metadata spreadsheet too, so please re-run that upload as well.

Same metadata link: Metadata is here: https://docs.google.com/spreadsheets/d/1vvIfJjYWGwOYe4GVhNt8gP9SWrC7Zd077Hko8jpH07Q/edit?usp=sharing

**Comment by sophialinn** [comment]
WAIT! Looks like Bus Stops is no longer in the GeoNode. Fine! But please do upload the metadata spreadsheet again.

**Comment by kalxas** [comment]
Done
