### ISSUE TITLE
Unable to access any layer detail page

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#231]
From the list of data layers, I'm trying to access *any* layer detail page and it's not going anywhere; just keeps spinning. I've restarted my browser and cleared my cache. Any ideas?

**Comment by sophialinn** [comment]
@kalxas Actually, the whole 2C GeoNode site seems to be down now.

**Comment by sophialinn** [comment]
@kalxas This error finally came up (after spinning for quite awhile):

An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the [error log](http://nginx.org/en/docs/ngx_core_module.html#error_log) for details.

Faithfully yours, OpenResty.

**Comment by kalxas** [comment]
Please try again now.

**Comment by sophialinn** [comment]
Yes, seems OK now. (Trying to make a minor metadata edit, but not able to save. I think this is another issue though...)
