### ISSUE TITLE
Big Search bar

### ISSUE THREAD

**Issue by milafrerichs** [state-hiu/2C-GeoNode#26]
Request via Google Doc:
> Remove Text filter and make the big “Search” area actually searchable

<img width="635" alt="bildschirmfoto 2017-08-24 um 14 52 47" src="https://user-images.githubusercontent.com/688980/29667232-ecbc647c-88db-11e7-9cb8-34bdbc1253d6.png">

**Comment by milafrerichs** [comment]
there are several places where the search is displayed.
For example in the Layer list page.
Adding the search bar would look something like that
<img width="1213" alt="bildschirmfoto 2017-08-24 um 14 50 55" src="https://user-images.githubusercontent.com/688980/29667291-199953b0-88dc-11e7-9222-088cfd1a9343.png">
would that be ok?

**Comment by d3netxer** [comment]
can we align the search bar to the left, so that is right next to the Explore Layers text on the right? The Upload Layers button can remain where it is on the right.

**Comment by d3netxer** [comment]
Since we are adding a large main search bar, then we should take out the smaller search box on the left menu.

**Comment by kalxas** [comment]
Fixed
