### ISSUE TITLE
Additional Search Fields (Have search work on description text in addition to just title) Ensure this works in autocomplete dropdowns etc

### ISSUE THREAD

**Issue by milafrerichs** [state-hiu/2C-GeoNode#28]
Text search
> Should search all attributes (title, abstract, keywords, metadata, etc.)

**Comment by kalxas** [comment]
- [ ] Autocomplete should start searching after the user provides at least X number of characters

**Comment by kalxas** [comment]
Autocomplete issue fixed in #130 and deployed to beta

**Comment by faithrs** [comment]
@kalxas Ready to be closed!
