### ISSUE TITLE
Add Categories as drop down in main nav bar

### ISSUE THREAD

**Issue by d3netxer** [state-hiu/2C-GeoNode#33]
Also, make sure the unique 2C categories are added.

<img width="816" alt="screen shot 2017-08-25 at 9 34 03 am" src="https://user-images.githubusercontent.com/2665840/29716245-a53fbf70-8978-11e7-9d95-b78c5efcc0f9.png">

**Comment by d3netxer** [comment]
no need to add icons, at least for now

**Comment by kalxas** [comment]
The Categories menu item has been implemented.
Needs review on beta site.
