### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by d3netxer** [state-hiu/2C-GeoNode#34]

**Comment by kalxas** [comment]
Action items:
- [ ] Decide if we want full https

**Comment by kalxas** [comment]
Full HTTPS enabled.

**Comment by faithrs** [comment]
@state-hiu-dev Tom can you please review this or mark it complete so we can close it?

**Comment by kalxas** [comment]
after this one is marked as complete, we will deploy on production and close the ticket

**Comment by d3netxer** [comment]
This looks good to me. It seems like the server is serving out both https and http services, which seems good to me!

**Comment by kalxas** [comment]
thanks @d3netxer

**Comment by kalxas** [comment]
@d3netxer I will need to deploy HTTPS to production in the following days. Can you please make sure that the 443 port is open in the Amazon Security Group for the production VM?

**Comment by d3netxer** [comment]
yes @kalxas I confirm that port 443 is open on production

**Comment by kalxas** [comment]
thanks @d3netxer

**Comment by kalxas** [comment]
When trying to install certbot on production machine, I got a broken package from Launchpad.
It seems that the packages were updated some days ago.
I have reported the issue upstream, we are now on hold until this is resolved in Launchpad...

**Comment by kalxas** [comment]
https://github.com/certbot/certbot/issues/5247

**Comment by kalxas** [comment]
it has been almost a week without a reply on the above ticket, so I will spend some time to fix this issue myself.

**Comment by kalxas** [comment]
So the problem has been fixed now and https is enabled on the production server

**Comment by kalxas** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=secondarycities.geonode.state.gov
