### ISSUE TITLE
Add filter for Data Provider Type

### ISSUE THREAD

**Issue by d3netxer** [state-hiu/2C-GeoNode#35]
Add filter for Data Provider Type:
- Global Downloaded Data
- Local Downloaded Data
- Local Authoritative Data
- Local Workshop Data

**Comment by kalxas** [comment]
Actually we might have a conflict in ISO with this field.
ISO includes ```CI_ResponsibleParty``` and a ```CI_RoleCode```attribute that can have the value of "Resource Provider" or "Data Provider", but there is no Data Provider Type.
And if we think about it, the above values refer to the data itself and not to the provider.

**Comment by waybarrios** [comment]
## Work in process

![image](https://user-images.githubusercontent.com/6794828/31136237-3cd5b916-a82d-11e7-9771-0be1802d09ac.png)

**Comment by kalxas** [comment]
Thanks @waybarrios

**Comment by kalxas** [comment]
The filter has been added and working on beta site.
Please review.
