### ISSUE TITLE
Add sign-in warning message

### ISSUE THREAD

**Issue by d3netxer** [state-hiu/2C-GeoNode#38]
warning message:

You are about to enter a Department of State computer system or network. Use by unauthorized persons, or for unauthorized personal business, is prohibited and may constitute a violation of 18 U.S.C. 1030 and other Federal law, as well as applicable Department policies and procedures.

You have NO REASONABLE EXPECTATION OF PRIVACY while using this computer system or network. All data contained and/or activities performed herein may be monitored, intercepted, recorded, read, copied, or captured in any manner by authorized personnel. System management personnel or supervisors may give law enforcement officials or appropriate Department managers any potential evidence of crime, fraud, or employee misconduct found on this computer system or network, and employees may be subject to discipline for misuse. Furthermore, law enforcement officials may be authorized to access and collect evidence from this computer system or network, or from any portable devices that have been connected to this computer system or network, therefore:

USE OF THIS COMPUTER SYSTEM OR NETWORK BY ANY USER, AUTHORIZED OR UNAUTHORIZED, CONSTITUTES EXPRESS CONSENT TO THIS MONITORING.

IF YOU DO NOT CONSENT TO THIS MONITORING, OR IF YOU ARE NOT AN AUTHORIZED USER, AND EXIT THIS SYSTEM.

IF YOU ARE AN AUTHORIZED USER AND CONSENT, BY SIGNING IN YOU INDICATE YOU AGREE TO ALL THE CONDITIONS STATED HEREIN.“

**Comment by d3netxer** [comment]
I added this to the base.html template

**Comment by kalxas** [comment]
@d3netxer your commit has been merged and deployed to production.
Can you please close this issue?

**Comment by d3netxer** [comment]
closed!
