### ISSUE TITLE
Check/verify how keywords are displayed and handled by the search engine

### ISSUE THREAD

**Issue by kalxas** [state-hiu/2C-GeoNode#50]

**Comment by kalxas** [comment]
Related to full text search which is implemented now.
Also, keywords are displayed in the same way as in CKAN now.

**Comment by faithrs** [comment]
@kalxas we talked about getting rid of the keywords in the menu on the left . . .

**Comment by kalxas** [comment]
@faithrs we just fixed it so the most popular keywords show up first.
I will deploy this on beta, we can definitely switch off if you want it off

**Comment by faithrs** [comment]
@kalxas see comment in #51

**Comment by kalxas** [comment]
Can we mark this one as reviewed and keep commenting on #51 ?

**Comment by kalxas** [comment]
Going to review the keyword filter, focusing on different browsers.
