### ISSUE TITLE
Add "Data Provider Type" and "City" fields in the Metadata form. AssignData Provider Type to appropriate in ISO and set City as a keyword

### ISSUE THREAD

**Issue by kalxas** [state-hiu/2C-GeoNode#55]
Assign Data Provider Type to appropriate place in ISO and set City as a keyword.

**Comment by kalxas** [comment]
Related to #35

**Comment by kalxas** [comment]
DataProviderType and City filters have been added.
Those fields will show up as a result of work being done in #59 
We just need to review the 2 filters and close this issue

**Comment by faithrs** [comment]
Ready to close.

**Comment by kalxas** [comment]
will move to production, thanks
