### ISSUE TITLE
Match field naming and order between spreadsheet and new metadata form and metadata preview + full html listing

### ISSUE THREAD

**Issue by kalxas** [state-hiu/2C-GeoNode#59]

**Comment by kalxas** [comment]
We are trying to finish this item this week.

**Comment by kalxas** [comment]
Now deployed on beta. Please review.

**Comment by schignel** [comment]
It looks like this is working great on the beta site--I think we can close and push to production.

**Comment by kalxas** [comment]
👍

**Comment by faithrs** [comment]
Ready to close.
