### ISSUE TITLE
Categories cleanup

### ISSUE THREAD

**Issue by kalxas** [state-hiu/2C-GeoNode#71]
Categories are not shown properly, lots of empty records.

**Comment by kalxas** [comment]
This is part of the Metadata Audit task (#72)

**Comment by kalxas** [comment]
We have already tested the process of deleting all current categories from the geonode database and restoring from the spreadsheet and looks good

**Comment by kalxas** [comment]
All categories now dropped on 2c.terranodo.io

**Comment by kalxas** [comment]
According to a message from @faithrs on Slack, the final Category list that was decided some time ago, does not match what we currently have deployed on the beta site.
This is not a development related issue, since the Categories list is auto-populated from the metadata spreadsheets.

**Comment by kalxas** [comment]
- [ ] Re-populate the Categories once the spreadsheets are reviewed.

**Comment by faithrs** [comment]
I believe Sophia found the problem in the Esmeraldas spreadsheet and fixed it. Categories in the drop down and in the menu on the left look good.

**Comment by faithrs** [comment]
The categories are correct but they are not laid out well in the filters menu on the left. Is there anything you can do to fix how they are displayed?

**Comment by kalxas** [comment]
Categories fixed in #133
