### ISSUE TITLE
Modification to base GeoNode repo to replace shopping cart icons in UI

### ISSUE THREAD

**Issue by kalxas** [state-hiu/2C-GeoNode#96]

**Comment by d3netxer** [comment]
Last here I searched and found replacement icons and documented them in this issue in the main Github GeoNode repo: https://github.com/GeoNode/geonode/issues/2762

**Comment by schignel** [comment]
This may already be planned, but I would suggest adding the option to download all of the selected layers: 

![mockup](https://user-images.githubusercontent.com/19474876/31149922-fd625090-a891-11e7-9672-5228976b18bb.png)

**Comment by d3netxer** [comment]
I made the shopping cart icons invisible on a fork and made a pull request here: https://github.com/state-hiu/2C-GeoNode/pull/141

**Comment by kalxas** [comment]
Thanks @d3netxer I will review and merge soon.
